## App property info
app:
  property:
    log-path: /mycloud/springcloud-app-salary/local-logs
    env: LOCAL

## Server info
server:
  port: 9211
  servlet:
    context-path: /app-salary

# Security info
security:
  oauth2:
    resource:
      # 定义一个回调URL调用Authorization Server来查看令牌是否有效
      userInfoUri: http://localhost:9141/server-auth/user

# DataSource Info
spring:
  datasource:
    jdbc-url: jdbc:hsqldb:mem:/app-salary
#    # Enable DDL Initialization
#    schema: classpath:schema.sql
#    # Enable DML Initialization
#    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## Eureka info
eureka:
  instance:
    # You need to change these, even for an Actuator application if you use a non-default context path or servlet path
    # https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.2.RELEASE/single/spring-cloud-netflix.html#_authenticating_with_the_eureka_server
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    # 注册服务的IP而不是服务器名称
    preferIpAddress: true
  client:
    # 向Eureka注册服务
    registerWithEureka: true
    # 拉取注册表的本地副本
    fetchRegistry: true
    serviceUrl:
      # 查询项目信息：<http://localhost:9121/server-eureka/eureka/apps/app-salary>
      defaultZone: http://localhost:9121/server-eureka/eureka/