## App property info
app:
  property:
    log-path: /mycloud/springcloud-app-client/default-logs
    env: DEFAULT

## Server info
server:
  port: 9231
  servlet:
    context-path: /app-client

# Security info
github:
  client:
    clientId: dd624e4f69e1cf794144
    clientSecret: 5e28e1456ad639bbf77b053adef87645d58492a4
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
myapp:
  client:
    clientId: client1
    clientSecret: client1-secret
    accessTokenUri: http://localhost:9141/server-auth/oauth/token
    userAuthorizationUri: http://localhost:9141/server-auth/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: http://localhost:9141/server-auth/user?client=myapp

## Spring info
spring:
  thymeleaf:
    # set false on develop
    cache: false

## Eureka info
eureka:
  instance:
    # You need to change these, even for an Actuator application if you use a non-default context path or servlet path
    # https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.2.RELEASE/single/spring-cloud-netflix.html#_authenticating_with_the_eureka_server
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    # 注册服务的IP而不是服务器名称
    preferIpAddress: true
  client:
    # 向Eureka注册服务
    registerWithEureka: true
    # 拉取注册表的本地副本
    fetchRegistry: true
    serviceUrl:
      # 查询项目信息：<http://localhost:9121/server-eureka/eureka/apps/server-auth>
      defaultZone: http://localhost:9121/server-eureka/eureka/